### PR TITLE
Fix for grabbing pixel data in latest OF version

### PR DESCRIPTION
**Pull request by TommyHardman**

### CODE REVIEW

**Comment by kalwalt** [comment]
@TommyHardman Thank you for this PR, I'm not using OpenFrameworks by a long time, but i think i should do other projects. I will test your changes, with which version are you refering?

**Comment by TommyHardman** [comment]
@kalwalt Hey! I'm using 0.10.1 but I believe every version from around 2017. They changed the way you access the raw pointer from an image. image.getPixels() changed to image.getPixels().getData()

**Comment by kalwalt** [comment]
@TommyHardman Testing the example included with your changes with the openFrameworks master branch i get this error:


```
/home/walter/kalwalt-github/openFrameworks/examples/skyboxExample/src/testApp.cpp: In member function ‘virtual void testApp::setup()’:
/home/walter/kalwalt-github/openFrameworks/examples/skyboxExample/src/testApp.cpp:12:9: error: ‘class ofCamera’ has no member named ‘cacheMatrices’
  camera.cacheMatrices(false) ;
         ^~~~~~~~~~~~~
/home/walter/kalwalt-github/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:215: recipe for target 'obj/linux64/Release/src/testApp.o' failed
make[1]: *** [obj/linux64/Release/src/testApp.o] Error 1
make[1]: uscita dalla directory "/home/walter/kalwalt-github/openFrameworks/examples/skyboxExample"
/home/walter/kalwalt-github/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:124: recipe for target 'Release' failed
make: *** [Release] Error 2

```

**Comment by TommyHardman** [comment]
@kalwalt Ah, the "cacheMatrices()" function seems to have been removed from ofCamera. Removing that line should work.

**Comment by kalwalt** [comment]
Yes that's true, but can you remove that line please? After that i can merge this... :slightly_smiling_face:

**Comment by kalwalt** [comment]
@TommyHardman perfect! i'm merging this and thanks for your contribution! I think I haven't looked at this code for years! I will do also other little improvements in the addon but i can do it by myself. :smile:

**Pull request merged**
